meta_name: "Code It"
meta_title: "Code It - Find your perfect business match"
meta_description: "Code It puts in relation companies and young coders to create creative projects."
meta_image: "favicon.png" # should exist in `app/assets/images/`
twitter_account: "@your_twitter_account"
